### ISSUE TITLE
Do hod wer des Büd glöscht ;(

### ISSUE THREAD

**Issue by SchopperAle** [OhlerJak/UebungenSEW3_2021#1]
#https://github.com/OhlerJak/UebungenSEW3_2021/commit/41e393cb084d243e12cf04605656678ec0cfd934
@OhlerJak
![EjSQh47WAAA8thU](https://user-images.githubusercontent.com/94116188/142861106-1a04b9b5-44b9-49b8-a4b5-b6fdb71bd929.jpg)

**Comment by SchopperAle** [comment]
> #[41e393c](https://github.com/OhlerJak/UebungenSEW3_2021/commit/41e393cb084d243e12cf04605656678ec0cfd934) @OhlerJak ![EjSQh47WAAA8thU](https://user-images.githubusercontent.com/94116188/142861106-1a04b9b5-44b9-49b8-a4b5-b6fdb71bd929.jpg)

https://user-images.githubusercontent.com/94116188/142861573-7f3dc38c-1ce3-4174-9ecf-e90b6b9016f7.mp4

**Comment by kainBurger** [comment]
https://bit.ly/3FTiJFL

**Comment by OhlerJak** [comment]
> 

![grafik](https://user-images.githubusercontent.com/94116072/143820953-50a63de9-0902-4126-a604-ff977f74172b.png)
imagine ma foit do eini

**Comment by kainBurger** [comment]
https://bit.ly/3dFRvWZ 😏

**Comment by kainBurger** [comment]
<img width="60" alt="gameOver" src="https://user-images.githubusercontent.com/94116352/150482092-91507c9c-7960-48c5-a32d-064af0fee836.png">
